package com.liang.bbs.article.persistence.mapper;

import com.liang.bbs.article.persistence.entity.PaperPo;
import com.liang.bbs.article.persistence.entity.PaperPoExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperPoExMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    long countByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int deleteByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int insert(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int insertSelective(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    List<PaperPo> selectByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    PaperPo selectPaperWithAuthors(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaperPo record, @Param("example") PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */

    List<PaperPo> selectRandom(Integer num);
    List<PaperPo> selectRandompaper(Integer num);
    List<HashMap<String,Integer>>  selectposbypaper(List<Integer> paperIds);
    List<Integer>  selectValidIds(Integer num);
    List<PaperPo> selectbyList(@Param("aIds")List<Integer> aIds);
}