package com.liang.bbs.article.persistence.mapper;

import com.liang.bbs.article.facade.dto.PaperDTO;
import com.liang.bbs.article.persistence.entity.PaperPo;
import com.liang.bbs.article.persistence.entity.PaperPoExample;

import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    long countByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int deleteByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int insert(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int insertSelective(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    List<PaperPo> selectByExampleWithBLOBs(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    List<PaperPo> selectByExample(PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    PaperPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaperPo record, @Param("example") PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PaperPo record, @Param("example") PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaperPo record, @Param("example") PaperPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PaperPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaperPo record);

    List<PaperDTO> selectAll();
}