package com.liang.bbs.article.persistence.mapper;

import com.liang.bbs.article.persistence.entity.RatePo;
import com.liang.bbs.article.persistence.entity.RatePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    long countByExample(RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int deleteByExample(RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int insert(RatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int insertSelective(RatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    List<RatePo> selectByExampleWithBLOBs(RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    List<RatePo> selectByExample(RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    RatePo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RatePo record, @Param("example") RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") RatePo record, @Param("example") RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RatePo record, @Param("example") RatePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(RatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_rating
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RatePo record);
}