package com.liang.bbs.article.persistence.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PaperPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.authors
     *
     * @mbg.generated
     */
    private String authors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.institution
     *
     * @mbg.generated
     */
    private String institution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.conference
     *
     * @mbg.generated
     */
    private String conference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.citations
     *
     * @mbg.generated
     */
    private Integer citations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.favorites
     *
     * @mbg.generated
     */
    private Integer favorites;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.abstracttext
     *
     * @mbg.generated
     */
    private String abstracttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_url
     *
     * @mbg.generated
     */
    private String paperUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.total_score
     *
     * @mbg.generated
     */
    private String totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.rating_count
     *
     * @mbg.generated
     */
    private Integer ratingCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.bio
     *
     * @mbg.generated
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}