package com.liang.bbs.article.persistence.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PaperPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public PaperPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andAuthorsIsNull() {
            addCriterion("authors is null");
            return (Criteria) this;
        }

        public Criteria andAuthorsIsNotNull() {
            addCriterion("authors is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorsEqualTo(String value) {
            addCriterion("authors =", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsNotEqualTo(String value) {
            addCriterion("authors <>", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsGreaterThan(String value) {
            addCriterion("authors >", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsGreaterThanOrEqualTo(String value) {
            addCriterion("authors >=", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsLessThan(String value) {
            addCriterion("authors <", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsLessThanOrEqualTo(String value) {
            addCriterion("authors <=", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsLike(String value) {
            addCriterion("authors like", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsNotLike(String value) {
            addCriterion("authors not like", value, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsIn(List<String> values) {
            addCriterion("authors in", values, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsNotIn(List<String> values) {
            addCriterion("authors not in", values, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsBetween(String value1, String value2) {
            addCriterion("authors between", value1, value2, "authors");
            return (Criteria) this;
        }

        public Criteria andAuthorsNotBetween(String value1, String value2) {
            addCriterion("authors not between", value1, value2, "authors");
            return (Criteria) this;
        }

        public Criteria andInstitutionIsNull() {
            addCriterion("institution is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionIsNotNull() {
            addCriterion("institution is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionEqualTo(String value) {
            addCriterion("institution =", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotEqualTo(String value) {
            addCriterion("institution <>", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionGreaterThan(String value) {
            addCriterion("institution >", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionGreaterThanOrEqualTo(String value) {
            addCriterion("institution >=", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLessThan(String value) {
            addCriterion("institution <", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLessThanOrEqualTo(String value) {
            addCriterion("institution <=", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLike(String value) {
            addCriterion("institution like", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotLike(String value) {
            addCriterion("institution not like", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionIn(List<String> values) {
            addCriterion("institution in", values, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotIn(List<String> values) {
            addCriterion("institution not in", values, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionBetween(String value1, String value2) {
            addCriterion("institution between", value1, value2, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotBetween(String value1, String value2) {
            addCriterion("institution not between", value1, value2, "institution");
            return (Criteria) this;
        }

        public Criteria andConferenceIsNull() {
            addCriterion("conference is null");
            return (Criteria) this;
        }

        public Criteria andConferenceIsNotNull() {
            addCriterion("conference is not null");
            return (Criteria) this;
        }

        public Criteria andConferenceEqualTo(String value) {
            addCriterion("conference =", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotEqualTo(String value) {
            addCriterion("conference <>", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceGreaterThan(String value) {
            addCriterion("conference >", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceGreaterThanOrEqualTo(String value) {
            addCriterion("conference >=", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceLessThan(String value) {
            addCriterion("conference <", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceLessThanOrEqualTo(String value) {
            addCriterion("conference <=", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceLike(String value) {
            addCriterion("conference like", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotLike(String value) {
            addCriterion("conference not like", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceIn(List<String> values) {
            addCriterion("conference in", values, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotIn(List<String> values) {
            addCriterion("conference not in", values, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceBetween(String value1, String value2) {
            addCriterion("conference between", value1, value2, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotBetween(String value1, String value2) {
            addCriterion("conference not between", value1, value2, "conference");
            return (Criteria) this;
        }

        public Criteria andCitationsIsNull() {
            addCriterion("citations is null");
            return (Criteria) this;
        }

        public Criteria andCitationsIsNotNull() {
            addCriterion("citations is not null");
            return (Criteria) this;
        }

        public Criteria andCitationsEqualTo(Integer value) {
            addCriterion("citations =", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsNotEqualTo(Integer value) {
            addCriterion("citations <>", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsGreaterThan(Integer value) {
            addCriterion("citations >", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsGreaterThanOrEqualTo(Integer value) {
            addCriterion("citations >=", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsLessThan(Integer value) {
            addCriterion("citations <", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsLessThanOrEqualTo(Integer value) {
            addCriterion("citations <=", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsIn(List<Integer> values) {
            addCriterion("citations in", values, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsNotIn(List<Integer> values) {
            addCriterion("citations not in", values, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsBetween(Integer value1, Integer value2) {
            addCriterion("citations between", value1, value2, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsNotBetween(Integer value1, Integer value2) {
            addCriterion("citations not between", value1, value2, "citations");
            return (Criteria) this;
        }

        public Criteria andFavoritesIsNull() {
            addCriterion("favorites is null");
            return (Criteria) this;
        }

        public Criteria andFavoritesIsNotNull() {
            addCriterion("favorites is not null");
            return (Criteria) this;
        }

        public Criteria andFavoritesEqualTo(Integer value) {
            addCriterion("favorites =", value, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesNotEqualTo(Integer value) {
            addCriterion("favorites <>", value, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesGreaterThan(Integer value) {
            addCriterion("favorites >", value, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesGreaterThanOrEqualTo(Integer value) {
            addCriterion("favorites >=", value, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesLessThan(Integer value) {
            addCriterion("favorites <", value, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesLessThanOrEqualTo(Integer value) {
            addCriterion("favorites <=", value, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesIn(List<Integer> values) {
            addCriterion("favorites in", values, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesNotIn(List<Integer> values) {
            addCriterion("favorites not in", values, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesBetween(Integer value1, Integer value2) {
            addCriterion("favorites between", value1, value2, "favorites");
            return (Criteria) this;
        }

        public Criteria andFavoritesNotBetween(Integer value1, Integer value2) {
            addCriterion("favorites not between", value1, value2, "favorites");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andPaperUrlIsNull() {
            addCriterion("paper_url is null");
            return (Criteria) this;
        }

        public Criteria andPaperUrlIsNotNull() {
            addCriterion("paper_url is not null");
            return (Criteria) this;
        }

        public Criteria andPaperUrlEqualTo(String value) {
            addCriterion("paper_url =", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlNotEqualTo(String value) {
            addCriterion("paper_url <>", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlGreaterThan(String value) {
            addCriterion("paper_url >", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlGreaterThanOrEqualTo(String value) {
            addCriterion("paper_url >=", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlLessThan(String value) {
            addCriterion("paper_url <", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlLessThanOrEqualTo(String value) {
            addCriterion("paper_url <=", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlLike(String value) {
            addCriterion("paper_url like", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlNotLike(String value) {
            addCriterion("paper_url not like", value, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlIn(List<String> values) {
            addCriterion("paper_url in", values, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlNotIn(List<String> values) {
            addCriterion("paper_url not in", values, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlBetween(String value1, String value2) {
            addCriterion("paper_url between", value1, value2, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andPaperUrlNotBetween(String value1, String value2) {
            addCriterion("paper_url not between", value1, value2, "paperUrl");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNull() {
            addCriterion("total_score is null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNotNull() {
            addCriterion("total_score is not null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreEqualTo(Integer value) {
            addCriterion("total_score =", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotEqualTo(Integer value) {
            addCriterion("total_score <>", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThan(Integer value) {
            addCriterion("total_score >", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_score >=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThan(Integer value) {
            addCriterion("total_score <", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThanOrEqualTo(Integer value) {
            addCriterion("total_score <=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIn(List<Integer> values) {
            addCriterion("total_score in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotIn(List<Integer> values) {
            addCriterion("total_score not in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreBetween(Integer value1, Integer value2) {
            addCriterion("total_score between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("total_score not between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andRatingCountIsNull() {
            addCriterion("rating_count is null");
            return (Criteria) this;
        }

        public Criteria andRatingCountIsNotNull() {
            addCriterion("rating_count is not null");
            return (Criteria) this;
        }

        public Criteria andRatingCountEqualTo(Integer value) {
            addCriterion("rating_count =", value, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountNotEqualTo(Integer value) {
            addCriterion("rating_count <>", value, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountGreaterThan(Integer value) {
            addCriterion("rating_count >", value, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("rating_count >=", value, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountLessThan(Integer value) {
            addCriterion("rating_count <", value, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountLessThanOrEqualTo(Integer value) {
            addCriterion("rating_count <=", value, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountIn(List<Integer> values) {
            addCriterion("rating_count in", values, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountNotIn(List<Integer> values) {
            addCriterion("rating_count not in", values, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountBetween(Integer value1, Integer value2) {
            addCriterion("rating_count between", value1, value2, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andRatingCountNotBetween(Integer value1, Integer value2) {
            addCriterion("rating_count not between", value1, value2, "ratingCount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}