package com.liang.bbs.article.persistence.entity;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class ScolarPoWithBLOBs extends ScolarPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_scholar.bio
     *
     * @mbg.generated
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_scholar.collaborator_ids
     *
     * @mbg.generated
     */
    private String collaboratorIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_scholar
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}